# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('instrument_choice', models.CharField(choices=[('clarinet', 'Clarinet'), ('acoustic guitar', 'Acoustic Guitar'), ('banjo', 'Banjo'), ('conga', 'Conga Set'), ('drum', 'Drum Set'), ('electric guitar', 'Electric Guitar'), ('piano', 'Piano'), ('sax', 'saxophone'), ('trumpet', 'Trumpet'), ('violin', 'Violin')], max_length=25)),
            ],
        ),
    ]
