# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrurent_app', '0002_auto_20170323_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_choice', models.CharField(choices=[('clarinet', 'Clarinet'), ('acoustic guitar', 'Acoustic Guitar'), ('banjo', 'Banjo'), ('conga', 'Conga Set'), ('drum', 'Drum Set'), ('electric guitar', 'Electric Guitar'), ('piano', 'Piano'), ('sax', 'saxophone'), ('trumpet', 'Trumpet'), ('violin', 'Violin')], max_length=25)),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
