# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrurent_app', '0003_auto_20170323_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='instrument_choice',
            field=models.CharField(choices=[('clarinet', 'Clarinet'), ('acoustic guitar', 'Acoustic Guitar'), ('banjo', 'Banjo'), ('conga', 'Conga Set'), ('drum', 'Drum Set'), ('electric guitar', 'Electric Guitar'), ('piano', 'Piano'), ('sax', 'Saxophone'), ('trumpet', 'Trumpet'), ('violin', 'Violin')], max_length=25),
        ),
    ]
