# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrurent_app', '0004_auto_20170323_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='instrument_quantity',
            field=models.IntegerField(default=1),
        ),
    ]
