# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 18:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instrurent_app', '0005_inventory_instrument_quantity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inventory',
            new_name='Instrument',
        ),
    ]
