# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 16:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instrurent_app', '0009_auto_20170405_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrument',
            name='instrument_description',
        ),
    ]
