# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrurent_app', '0010_remove_instrument_instrument_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='instrument_description',
            field=models.CharField(default=2000, max_length=2000),
            preserve_default=False,
        ),
    ]
