# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrurent_app', '0011_instrument_instrument_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='instrument_choice',
            field=models.CharField(choices=[('Clarinet', 'clarinet'), ('Acoustic Guitar', 'acoustic guitar'), ('banjo', 'Banjo'), ('conga', 'Conga Set'), ('drum', 'Drum Set'), ('electric guitar', 'Electric Guitar'), ('piano', 'Piano'), ('sax', 'Saxophone'), ('trumpet', 'Trumpet'), ('violin', 'Violin')], max_length=25),
        ),
    ]
