# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrurent_app', '0012_auto_20170405_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='instrument_price',
            field=models.IntegerField(default=810),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='instrument',
            name='instrument_choice',
            field=models.CharField(max_length=25),
        ),
    ]
