# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrurent_app', '0013_auto_20170405_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='instrument_price',
            field=models.FloatField(),
        ),
    ]
