# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrurent_app', '0014_auto_20170405_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='instrument_image',
            field=models.CharField(default=200, max_length=300),
            preserve_default=False,
        ),
    ]
