# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrurent_app', '0015_instrument_instrument_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='instrument_quantity',
            field=models.IntegerField(default=50),
        ),
    ]
